### ISSUE TITLE
AttributeError using /ingest

### ISSUE THREAD

**Issue by kfeeeeee** [atisharma/llama_farm#1]
Hi,

first of all thank for your great project! Whenever I invoke "/ingest" and regardless of the given input (urls, filnames, dir) it throws an AttributeError, e.g. /ingest "text.txt" will throw

`AttributeError: 'list' object has no attribute 'decode'
`

The trace is barely readable so could you please check if you are having the same issue?
Am I doing something wrong here?

**Comment by atisharma** [comment]
Sorry and thank you for the bug report. I somehow committed a horrible typo. Please pull and try it now.

**Comment by atisharma** [comment]
No feedback and it's fixed so far as I can see, so closing.

**Comment by kfeeeeee** [comment]
Thank you for the fast fix! It's working now pretty great!
