### ISSUE TITLE
hy.reader error

### ISSUE THREAD

**Issue by hellofable** [atisharma/llama_farm#10]
Hi there. When I run llama_farm I get this error :

> hy.reader.exceptions.LexException: reader macro '#^list' is not defined

Ideas? Thanks

**Comment by atisharma** [comment]
Hi, I need to know more here to be sure, but perhaps you have the wrong version of hy and hyrule installed? Did you install from the `requirements.txt` file? Are you using a virtual environment (venv)?

**Comment by joshuachris2001** [comment]
I don't mean to poke at a old thread but I'm having the same error. I am using the dev branch I forcefully reinstalled hy and hyrule. running the program in venv and an Alpine docker env [py3-pip, python3-dev, make, gcc, g++], same error. I am using the `requirements.txt` file.
with the issue I can't get very far.
same error with `pip install git+https://github.com/atisharma/llama_farm`

**Comment by atisharma** [comment]
Thanks. I was able to reproduce the error. It seems some type hints I was using were causing problems. I just removed them. It should be fine now.
